<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blog</string>
		<string>dblog</string>
		<string>mblog</string>
		<string>eblog</string>
		<string>qblog</string>
	</array>
	<key>name</key>
	<string>BLOG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(type|origin|distinct|random|fixed|case|if|then|else|query|obs|exists|for|in|with|return|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.control.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line comments</string>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Block comments</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.blog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.blog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>\b([A-Z][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>storage.type.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Functions: name( ... )</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.blog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()</string>
			<key>name</key>
			<string>meta.function-call.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>(==|=|!=|&amp;|\||\+|-|\*|/|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Braces</string>
			<key>match</key>
			<string>[\{\}\[\]\(\)]</string>
			<key>name</key>
			<string>punctuation.bracket.blog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Case arm labels like [A,B] in case syntax</string>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.case-label.blog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9_,\s]+</string>
					<key>name</key>
					<string>constant.other.symbol.blog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function names ending with '('</string>
			<key>match</key>
			<string>\b(\w+)\(</string>
			<key>name</key>
			<string>function.blog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blog</string>
	<key>uuid</key>
	<string>99d32618-4b9c-4a4c-b44b-fb8851e307be</string>
</dict>
</plist>